git:
  # The main branches. We colour commits green if they belong to one of these branches,
  # so that you can easily see which commits are unique to your branch (coloured in yellow)
  mainBranches: [master, main]
gui:
  border: 'rounded' # one of 'single' | 'double' | 'rounded' | 'hidden'
  showIcons: false
  showFileTree: true # for rendering changes files in a tree format
  showListFooter: true # for seeing the '5 of 20' message in list panels
  experimentalShowBranchHeads: false # visualize branch heads with (*) in commits list
  nerdFontsVersion: "3"

  # Color theme choices
  #
  # Tokyo Night - Night
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#27a1b9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
  #
  # Tokyo Night - Moon
  # theme:
  #   activeBorderColor:
  #     - "#ff966c"
  #     - "bold"
  #   inactiveBorderColor:
  #     - "#589ed7"
  #   searchingActiveBorderColor:
  #     - "#ff966c"
  #     - "bold"
  #   optionsTextColor:
  #     - "#82aaff"
  #   selectedLineBgColor:
  #     - "#2d3f76"
  #   cherryPickedCommitFgColor:
  #     - "#82aaff"
  #   cherryPickedCommitBgColor:
  #     - "#c099ff"
  #   markedBaseCommitFgColor:
  #     - "#82aaff"
  #   markedBaseCommitBgColor:
  #     - "#ffc777"
  #   unstagedChangesColor:
  #     - "#c53b53"
  #   defaultFgColor:
  #     - "#c8d3f5"
  #
  # Monokai Theme
  # theme:
  #   activeBorderColor:
  #     - "#62d8f1"
  #     - "bold"
  #   inactiveBorderColor:
  #     - "#8a8a8a"
  #   searchingActiveBorderColor:
  #     - "#62d8f1"
  #     - "bold"
  #   optionsTextColor:
  #     - "#ff9700"
  #   selectedLineBgColor:
  #     - "#404040"
  #   cherryPickedCommitFgColor:
  #     - "#62d8f1"
  #   cherryPickedCommitBgColor:
  #     - "#fc1a70"
  #   markedBaseCommitFgColor:
  #     - "#62d8f1"
  #   markedBaseCommitBgColor:
  #     - "#ffff87"
  #   unstagedChangesColor:
  #     - "#25394b"
  #   defaultFgColor:
  #     - "#ffffff"
  #   authorColors:
  #     "*": "#fc1a70"
  #
  # Gruvebox Theme
  # theme:
  #   activeBorderColor: ['#b8bb26']
  #   inactiveBorderColor: ['#3c3836']
  #   optionsTextColor: ['#b8bb26']
  #   selectedLineBgColor: ['#3c3836']
  #   inactiveViewSelectedLineBgColor: ['#d7d3d1']
  #   cherryPickedCommitFgColor: ['#b8bb26']
  #   cherryPickedCommitBgColor: ['#3c3836']
  #   markedBaseCommitFgColor: ['#d3869b']
  #   markedBaseCommitBgColor: ['#3c3836']
  #   unstagedChangesColor: ['#fb4934']
  #   defaultFgColor: ['#ebdbb2']
  #
  # Dracula
  # theme:
  #   activeBorderColor:
  #     - "#FF79C6"
  #     - bold
  #   inactiveBorderColor:
  #     - "#BD93F9"
  #   searchingActiveBorderColor:
  #     - "#8BE9FD"
  #     - bold
  #   optionsTextColor:
  #     - "#6272A4"
  #   selectedLineBgColor:
  #     - "#6272A4"
  #   inactiveViewSelectedLineBgColor:
  #     - bold
  #   cherryPickedCommitFgColor:
  #     - "#6272A4"
  #   cherryPickedCommitBgColor:
  #     - "#8BE9FD"
  #   markedBaseCommitFgColor:
  #     - "#8BE9FD"
  #   markedBaseCommitBgColor:
  #     - "#F1FA8C"
  #   unstagedChangesColor:
  #     - "#FF5555"
  #   defaultFgColor:
  #     - "#F8F8F2"

  # Catppuccin Mocha Rosewater
  # theme:
  #   activeBorderColor:
  #     - '#f5e0dc'
  #     - bold
  #   inactiveBorderColor:
  #     - '#a6adc8'
  #   optionsTextColor:
  #     - '#89b4fa'
  #   selectedLineBgColor:
  #     - '#313244'
  #   cherryPickedCommitBgColor:
  #     - '#45475a'
  #   cherryPickedCommitFgColor:
  #     - '#f5e0dc'
  #   unstagedChangesColor:
  #     - '#f38ba8'
  #   defaultFgColor:
  #     - '#cdd6f4'
  #   searchingActiveBorderColor:
  #     - '#f9e2af'
  #
  # authorColors:
  #   '*': '#b4befe'

  # Catppuccin Mocha Sapphire
  # theme:
  #   activeBorderColor:
  #     - '#74c7ec'
  #     - bold
  #   inactiveBorderColor:
  #     - '#a6adc8'
  #   optionsTextColor:
  #     - '#89b4fa'
  #   selectedLineBgColor:
  #     - '#313244'
  #   cherryPickedCommitBgColor:
  #     - '#45475a'
  #   cherryPickedCommitFgColor:
  #     - '#74c7ec'
  #   unstagedChangesColor:
  #     - '#f38ba8'
  #   defaultFgColor:
  #     - '#cdd6f4'
  #   searchingActiveBorderColor:
  #     - '#f9e2af'
  #
  # authorColors:
  #   '*': '#b4befe'

customCommands:
  - key: "N"
    context: "files"
    command: "git commit --no-verify"
    description: "Commit without hooks"
    subprocess: true
